apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: test-home
spec:
  kubeConfig:
    secretRef:
      name: gitops-reconciler-kubeconfig
      key: kubeconfig
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: tenant-bootstrap
  path: ./infrastructure/namespaces/dev
  prune: true
  wait: true
  timeout: 5m0s
